# Generated by Django 5.0.6 on 2024-06-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaileAttemptsLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
