# Generated by Django 5.0.6 on 2024-06-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lockout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
